### ISSUE TITLE
Create presentation items

### ISSUE THREAD

**Issue by milestweed** [milestweed/senior_marketing_optimization#2]
**Tasks**

- [x] Create pipeline diagram
- [x] develop possible GPT prompts
- [x] mock up expected output/vizualizations
